### ISSUE TITLE
In manip.py

### ISSUE THREAD

**Issue by CottetE** [oci1315/csudoci#2]
Test sur terminal C9 :

```
Traceback (most recent call last):
  File "manip.py", line 74, in <module>
    test()
  File "manip.py", line 63, in test
    tree = HTMLTreeParser(test_html).get_tree()
  File "/usr/local/lib/python3.4/dist-packages/csudoci/html/parser.py", line 22, in __init__
    self.feed(html)
  File "/usr/lib/python3.4/html/parser.py", line 165, in feed
    self.goahead(0)
  File "/usr/lib/python3.4/html/parser.py", line 216, in goahead
    self.handle_data(rawdata[i:j])
  File "/usr/local/lib/python3.4/dist-packages/csudoci/html/parser.py", line 90, in handle_data
    stack=self.stack
csudoci.html.parser.MyHTMLParseError: Trouvé les données '
    ' en dehors de toute balise
```

**Comment by donnerc** [comment]
Merci pour le signalement de bug ! Le code de `parser.py` détectait en fait des erreurs de syntaxe qui n'existaient pas, car il traitait les espaces et les retours à la ligne comme des données qui ne devaient pas se trouver en dehors d'une balise.
